# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application using AWS Lambda

Resources:
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/py_aws_lambda.handler.users_handler.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /py-aws-lambda/users/{id}
            Method: get
        CreateUser:
          Type: Api
          Properties:
            Path: /py-aws-lambda/users
            Method: post
        UpdateUser:
          Type: Api
          Properties:
            Path: /py-aws-lambda/users/{id}
            Method: put
        DeleteUser:
          Type: Api
          Properties:
            Path: /py-aws-lambda/users/{id}
            Method: delete

  AddressesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/py_aws_lambda.handler.addresses_handler.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetAddress:
          Type: Api
          Properties:
            Path: /py-aws-lambda/addresses/{id}
            Method: get
        CreateAddress:
          Type: Api
          Properties:
            Path: /py-aws-lambda/addresses
            Method: post
        UpdateAddress:
          Type: Api
          Properties:
            Path: /py-aws-lambda/addresses/{id}
            Method: put
        DeleteAddress:
          Type: Api
          Properties:
            Path: /py-aws-lambda/addresses/{id}
            Method: delete

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

Outputs:
  UsersFunction:
    Description: "Users Lambda Function ARN"
    Value: !GetAtt UsersFunction.Arn
  AddressesFunction:
    Description: "Addresses Lambda Function ARN"
    Value: !GetAtt AddressesFunction.Arn
